// fspt3-vue-portfolio-pannachow/src/components/AdminView.vue
<template>
  <div>
    <h3>ADD NEW PROJECT</h3>

    <div class="horizontal">
      <div class="field">
        <label for="pt">Project Title</label>
        <br />
        <input id="pt" type="text" v-model="title" />
      </div>

      <div class="field">
        <label for="url">Image URL</label>
        <br />
        <input id="url" type="text" v-model="image" />
      </div>
    </div>

    <div class="field">
      <label for="pd">Project Description</label>
      <br />
      <textarea id="pd" v-model="description"></textarea>
    </div>

    <button @click="handleSubmit">SUBMIT</button>
  </div>
</template>

<script>
export default {
  name: "AdminView",
  data() {
    return {
      title: "",
      image: "",
      description: "",
      id: 4
    };
  },
  methods: {
    handleSubmit() {
      this.$emit("createProject", {
        title: this.title,
        image: this.image,
        description: this.description,
        id: this.id++
      });
    }
  }
};
</script>

<style>
.horizontal {
  display: grid;
  grid-template-columns: 1fr 1fr;
  justify-content: space-between;
  gap: 10px;
  margin-bottom: 20px;
}

.field {
  text-align: left;
  width: 100%;
  margin-bottom: 20px;
}
</style>

// fspt3-react-porfolio-pannachow/src/components/adminView.js
import React from "react";

class AdminView extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      url: "",
      title: "",
      description: ""
    };
  }

  handleInputChange(event) {
    const value = event.target.value;
    const name = event.target.name;

    this.setState({
      [name]: value
    });
  }

  handleSubmit() {
    this.props.addProject({
      title: this.state.title,
      image: this.state.image,
      description: this.state.description,
    });
  }


  render() {
    return (
      <div className="AdminView">
        <h1>MY PORTFOLIO</h1>
        <h2>Add New Project</h2>
        <form>
          <div class="horizontal">
            <label class="field">
              Project Title
              <input name="title" onChange={e => this.handleInputChange(e)} />
            </label>

            <label class="field">
              Image URL
              <input name="image" onChange={e => this.handleInputChange(e)} />
            </label>
          </div>

          <label class="field">
            Project Description
            <textarea name="description" onChange={e => this.handleInputChange(e)} />
          </label>
        </form>
        <button onClick={() => this.handleSubmit()}>Submit</button>
      </div>
    );
  }
}

export default AdminView;
