// fspt3-vue-portfolio-pannachow/src/components/UserView.vue
<template>
  <div>
    <!-- Add a featured image section  -->
    <div class="horizontal">
      <div class="field">
        <img
          id="featured-img"
          class="image"
          v-bind:src="featuredProject.image"
        />
      </div>

      <div class="field">
        <h2 id="fpt">{{ featuredProject.title }}</h2>
        <p id="fpd">{{ featuredProject.description }}</p>
      </div>
    </div>

    <!-- Insert img, url, description -->
    <div id="images">
      <img
        @click="featuredProject = project"
        class="image"
        v-for="project in projects"
        :src="project.image"
        :key="project.id"
      />
    </div>
  </div>
</template>

<script>
export default {
  name: "UserView",
  props: ["projects"],
  data() {
    return {
      featuredProject: this.projects[0]
    };
  }
};
</script>

<style>
#images {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 10px;
}

.image {
  width: 100%;
}
</style>

// fspt3-react-porfolio-pannachow/src/components/userView.js
import React from "react";

class UserView extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      featuredProject: this.props.projects[0]
    };
  }

  setFeaturedProject(project) {
    this.setState({ featuredProject: project });
  }

  render() {
    return (
      <div className="UserView">
        <h1>User View</h1>
        <div class="horizontal">
          <div class="field">
            <img
              alt={this.state.featuredProject.description}
              id="featured-img"
              src={this.state.featuredProject.image}
            />
          </div>

          <div class="field">
            <h2 id="fpt">{this.state.featuredProject.title}</h2>
            <p id="fpd">{this.state.featuredProject.description}</p>
          </div>
        </div>

        <div id="images">
          {this.props.projects.map((project) => (
            <img
              alt={project.description}
              onClick={() => this.setFeaturedProject(project)}
              class="image"
              src={project.image}
            />
          ))}
        </div>
      </div>
    );
  }
}

export default UserView;
